AWSTemplateFormatVersion: '2010-09-09'
Description: >-
  This template creates a secure, read-only IAM Role for Loxe AI Evidence Tracer
  to access AWS resources for SOC 2 compliance evidence gathering.

Parameters:
  ExternalId:
    Type: String
    Description: The unique External ID provided by Loxe AI to ensure secure cross-account access.


  LoxeAppAwsAccountId:
    Type: String
    Description: The 12-digit AWS Account ID for the Loxe AI application.

Resources:
  LoxeReadOnlyRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Ref LoxeAppAwsAccountId
            Action: 'sts:AssumeRole'
            Condition:
              StringEquals:
                'sts:ExternalId': !Ref ExternalId
      # This section attaches the read-only permissions to the role.
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/ReadOnlyAccess'
        - 'arn:aws:iam::aws:policy/AWSCloudTrail_ReadOnlyAccess'

Outputs:
  # This section defines what information is returned to the user after the stack is created.
  RoleArn:
    Description: The ARN of the created IAM role for Loxe AI.
    Value: !GetAtt LoxeReadOnlyRole.Arn